### ISSUE TITLE
Incorrect decompilation output (hello world with message boxes)

### ISSUE THREAD

**Issue by megacoderencoderdecoder** [avast/retdec#708] opened 2020-02-11 14:10 UTC
**I create simple hello world project and can't get correct decompilation output with latest retdec!**

**Input code:** 
```
#include <Windows.h>
void MessageBoxA_test1(const char* message, const char* header)
{
	MessageBoxA(0, message, header, 0);
}
int main()
{
	MessageBoxA_test1("Hello", "World");
	MessageBoxA_test1("World", "Hello");
}
```

**Retdec output :** https://pastebin.com/bsnT1Ecb

**1.** I can't find main function 
**2.** I can't find **MessageBoxA_test1("Hello", "World") call**
**3.** No 'Hello' and 'World' lines in output;

For compare **snowman output:** https://pastebin.com/7pHj1z6C
**1.** I see correct main func 
**2.** I see correct MessageBoxA_test1("Hello","World") calling!
```
uint32_t fun_14001118b(int64_t rcx, int64_t rdx, int64_t r8) {
    int32_t ecx4;
 
    ecx4 = 58;
    while (ecx4) {
        --ecx4;
    }
    fun_140011082(0x140020012);
    fun_140011208("Hello", "World");
    fun_140011208("World", "Hello");
    return 0;
}
```

And input binary (x64 Windows, build Visual Studio 2019) : 
[TestRetdec2.zip](https://github.com/avast/retdec/files/4186063/TestRetdec2.zip)

**Comment by megacoderencoderdecoder** [comment] 2020-02-11 16:18
@s3rvac, you don't know, this is error in retdec or not ?

**Comment by xkubov** [comment] 2020-02-11 20:03
Well, I cannot tell from the C output only, but as you have suggested, this may be caused by the wrong convention being used. This is mainly caused because the signature of the function is not known as the function was not recognized and the fallback convention is used. We are currently working on letting users specify info (among which is calling convention) by various methods (for example, some third party frontend), which might help to solve this issue for you.

**Comment by megacoderencoderdecoder** [comment] 2020-02-11 20:07
@xkubov in this 'hello world' i use default calling convention. And i no enter calling convention in snowman decompiler, and got correct result.

**Comment by xkubov** [comment] 2020-02-11 20:17
Well, even the default convention might not be the same as the fallback convention in RetDec analysis. I am grateful for your remarks and we will certainly benefit from it.

When it comes to the global strings, the most definitely were discarded by the used LLVM optimizations. Generally in compilers when some code is not being used it is discarded. This sometimes helps as it discards lot of garbage on output but also in some cases (like yours) it may discard some important strings when the decompiler failed in some analysis (like analysis of calling convention).

**Comment by megacoderencoderdecoder** [comment] 2020-02-11 20:21
@xkubov I see '**Hello**' and '**World**' strings in 'TestRetdec2.exe.**dsm**' and in 'TestRetdec2.exe.**ll**' files.

**Comment by megacoderencoderdecoder** [comment] 2020-02-11 20:23
But strange.... I can't find any references for this strings in these files....

**Comment by megacoderencoderdecoder** [comment] 2020-02-12 12:25
@xkubov @s3rvac i found! This is error in **'-register-localization'** _(this cause lost global vars)_

**Comment by xkubov** [comment] 2020-02-12 14:23
Thank you for the analysis but the problem is not in the register localization. The real problem was as I said is in the analysis of parameters. 

On x64 architecture, there is a difference between the Microsoft x64 and Unix ABI. In RetDec there was a wrong condition for detection of Microsoft x64 ABI. I have managed to correct this condition and get the following output:

```
  int64_t function_140011780(void) {
      // 0x140011780
      int64_t v1; // bp-248, 0x140011780
      __asm_rep_stosd_memset((char *)&v1, -0x33333334, 58);
      function_140011082(&g53);
      function_140011208("Hello", "World");
      function_140011208("World", "Hello");
      return 0;
  }
```
As you can see it is more what you would expect to get.

As a side note: I played with the RetDec radare2 plugin with this binary and got an even better result by altering names and so on:

```
void main_wrap(int32_t a, int32_t b) {
    // 0x140011780
    int64_t v1; // bp-248, 0x140011780
    __asm_rep_stosd_memset((char *)&v1, -0x33333334, 58);
    unkown((int32_t)&g1, b);
    MessageBoxA_test1("Hello", "World");
    MessageBoxA_test1("World", "Hello");
}

```

**Comment by xkubov** [comment] 2020-02-12 14:26
I will run the changes on our test set and will provide you with details when the changes are merged into master. Thank you for your input on x64 binaries.

**Comment by xkubov** [comment] 2020-02-12 15:11
So, your error should be solved by 6cc12004. I've managed to get all expected parameters of the function, as can be seen above. If you find another place where we could improve the decompilation of x64 binaries feel free to open a new issue.

**Closed by xkubov** 2020-02-12 15:11 UTC
Labels: C-bin2llvmir, bug

**Comment by megacoderencoderdecoder** [comment] 2020-02-12 16:12
@xkubov thanks!!!

**Comment by megacoderencoderdecoder** [comment] 2020-02-12 16:23
@xkubov i download latest TeamCity build **Time Date Stamp:              	5E4419B5h  -> 12/02/2020  18:28:53**  
But see same problem.
```
int64_t function_140011780(int64_t a1) {
    // 0x140011780
    int64_t v1; // bp-248, 0x140011780
    __asm_rep_stosd_memset((char *)&v1, -0x33333334, 58);
    bool v2; // 0x140011780
    function_140011082((v2 ? -232 : 232) + (int64_t)&v1);
    function_140011208();
    function_140011208();
    return 0;
}
```
Now even 'system' function call is lost!!!

**Comment by xkubov** [comment] 2020-02-12 16:43
Did you try this build? https://retdec-tc.avast.com/viewLog.html?buildId=3477&buildTypeId=Retdec_WinBuild&tab=artifacts

This should be the latest working version. I have checked on a clean build (on macOS) and the output was the same as above.

**Comment by megacoderencoderdecoder** [comment] 2020-02-12 16:52
**Time Date Stamp:              	5E442346h  -> 12/02/2020  19:09:42**  
```
// Address range: 0x140011780 - 0x1400117dc
int64_t function_140011780(void) {
    // 0x140011780
    int64_t v1; // bp-248, 0x140011780
    __asm_rep_stosd_memset((char *)&v1, -0x33333334, 58);
    function_140011082(&g53);
    function_140011208("Hello", "World");
    function_140011208("World", "Hello");
    return 0;
}
```
@xkubov now all works
