### ISSUE TITLE
PowerPc Error: Decompilation of file xx.bin.bc failed

### ISSUE THREAD

**Issue by szpiner** [avast/retdec#712] opened 2020-02-14 12:34 UTC
Hi,
i did tried several settings to decompile PowerPC codeFlash without success. File in binnary and hex format have already s3rvac(i want share it public). --no-memory-limit already tried too. Logs attached.
[logPowerPcRetDec.zip](https://github.com/avast/retdec/files/4204447/logPowerPcRetDec.zip)

**Comment by s3rvac** [comment] 2020-02-14 16:04
Hi, thank you for the report. From the logs, the decompilation fails with
```
Running phase: removing functions prefixed with [__decompiler_undefined_function_] ( 232.39s )
Error: Decompilation of file C:\Users\User\Desktop\LF\retdec\bin\c_flash.bin.bc failed
```
This is most probably the same situation as in #47 (insufficient stack space). I will try decompiling the file on Linux with increased stack size and will let you know if this is indeed the same issue or a different one.

**Comment by s3rvac** [comment] 2020-02-14 18:30
I was able to decompile the file via the provided command on Linux with the current `master` version of RetDec when increasing the available stack space. I have sent you the output via email. I am closing the issue as a duplicate of #47. See [this comment](https://github.com/avast/retdec/issues/47#issuecomment-352692117) for possible workarounds.

**Closed by s3rvac** 2020-02-14 18:30 UTC
Labels: C-llvmir2hll, P-run

**Comment by szpiner** [comment] 2020-02-14 18:34
Thanks for solution and output.
