### ISSUE TITLE
label lab_generated_0 not declared and goto referencing it in decompile inner worlds

### ISSUE THREAD

**Issue by jopadan** [avast/retdec#673] opened 2019-10-27 20:27 UTC
Using retdec-decompiler with sleepless inner worlds inner elf32 binary

**Comment by xkubov** [comment] 2019-11-25 15:38
Hi, are you able to provide (either here or by sending it to my email address) the binary file you have tried to decompile? Otherwise, I won't be able to reproduce your issue.

**Comment by jopadan** [comment] 2019-11-25 20:44
https://archive.org/details/iw12-linux

**Comment by xkubov** [comment] 2019-11-27 13:31
So the issue is that after decompilation of the provided file, the generated C does not contain a label, to which a `goto` statement jumps. As @jopadan states, code contains `goto lab_generated_0`, which seems to provide info about the unsuccessful generation of the label on specified address. By briefly looking at the disassembly, this line is represented by the `goto` statement:

```
0x801bf60:   75 0a                    jne 0x801bf6c <function_801bf40+0x2c>
```

So the label should be `lab_801bf6c`.

As the #536 describes same problem I am closing this issue.

**Closed** 2019-11-27 13:31 UTC
