### ISSUE TITLE
decompilation of simple golang hello dies in a wrongly quoted json config

### ISSUE THREAD

**Issue by cipy** [avast/retdec#792] opened 2020-07-02 07:17 UTC
$ cat hello.go 
package main

import "fmt"

func main() {
        fmt.Printf("Hello\n")
}

$ GOOS=windows GOARCH=386 go build -o hello.com hello.go

$ retdec-decompiler.py hello.exe

...

RUN: retdec-llvmir2hll -target-hll=c -output-format=plain -var-renamer=readable -var-name-gen=fruit -var-name-gen-prefix= -call-info-obtainer=optim -arithm-expr-evaluator=c -validate-module -o hello.exe.c hello.exe.bc -enable-debug -emit-debug-comments -config-path=hello.exe.config.json -max-memory-half-ram
Running phase: initialization ( 0.22s )
 -> creating the used HLL writer [c] ( 0.22s )
 -> creating the used alias analysis [simple] ( 0.22s )
 -> creating the used call info obtainer [optim] ( 0.22s )
 -> creating the used evaluator of arithmetical expressions [c] ( 0.22s )
 -> creating the used variable names generator [fruit] ( 0.22s )
 -> creating the used variable renamer [readable] ( 0.22s )
 -> creating the used semantics [libc,gcc-general,win-api] ( 0.22s )
 -> loading the input config ( 0.22s )
Error: Loading of the config failed: Invalid encoding in string. @ line = **206892**, column = 31.

aka

                {
                    "name": ",
                    "realName": ",
                    "isFromDebug": true,
                    "type": {
                        "llvmIr": "i32"
                    }
                },

**Comment by xkubov** [comment] 2020-07-09 09:06
Hi, thank you for the report. Can confirm that this is happening on the current RetDec master. Someone will take a look at this shortly.

**Comment by cipy** [comment] 2020-07-09 15:22
Hi,

I can confirm it's in your recent retdec-v4.0-macos-64b.tar.xz release

**Comment by xkubov** [comment] 2020-08-01 20:23
So, by looking at the config we can see that the problem is with serialized arguments:

<table>
<td>RetDec config</td><td>Log from parameter analysis</td></br>
<tr>
<td><img src="https://user-images.githubusercontent.com/36452497/89109534-50fe6200-d442-11ea-8d18-cdfffa5de87d.png" alt="Problematic argument in config" width="300" height="450"></td>
<td><img src="https://user-images.githubusercontent.com/36452497/89109548-6f645d80-d442-11ea-9e32-a32b963d3cd3.png" alt="Problematic argument in log" width="250" height="200"></td>
</table>

So I dug into the serialization/deserialization module and found out that we are currently using ASCII Typeformat for Rapidjson writer instead of UTF8 one that is the default. Is there a reason for this @PeterMatula? Or can we merge fix into master? (https://github.com/avast/retdec/commit/5c3e00744c6555815440833ac281b36a533ca2b2)

I have changed the Typeformat to UTF8, and decompilation was successful.

As I was expecting character handling is implemented in `llvmir2hll` so the result of decompilation is (epsilon is not in output):
```c
void strconv_adjustLastDigitFixed(int32_t d, uint32_t num, uint32_t den, uint32_t shift, int32_t _ce__b5_, uint32_t _7e_r5);
```

**Comment by xkubov** [comment] 2020-08-04 16:19
Hi, fix for this issue is now merged to master. I am closing this issue.

**Closed by xkubov** 2020-08-04 16:19 UTC
Labels: C-config, bug
