### ISSUE TITLE
Fails to build on Arch Linux yarac issue

### ISSUE THREAD

**Issue by ahmedselim2017** [avast/retdec#726] opened 2020-03-22 19:34 UTC
When I run ```make install``` for building from source, it gives this error:
```
...
-- Compiling: /home/tozkoparan/retdec/share/retdec/support/generic/yara_patterns/static-code/pe/32/le/x86/x86-debug-vs-2008.yara
-- Compiling: /home/tozkoparan/retdec/share/retdec/support/generic/yara_patterns/static-code/pe/64/le/x86/x64-vs-2015.yara
-- Compiling: /home/tozkoparan/retdec/share/retdec/support/generic/yara_patterns/static-code/pe/64/le/x86/x64-vs-2012.yara
-- Compiling: /home/tozkoparan/retdec/share/retdec/support/generic/yara_patterns/static-code/pe/64/le/x86/x64-debug-vs-2015.yara
error: 58
Error: yarac failed during compilation of file /home/tozkoparan/retdec/share/retdec/support/generic/yara_patterns/static-code/pe/32/le/x86/x86-debug-vs-2008.yara
error: 58
Error: yarac failed during compilation of file /home/tozkoparan/retdec/share/retdec/support/generic/yara_patterns/static-code/pe/32/le/x86/x86-debug-vs-2010.yara
error: 58
error: 58
Error: yarac failed during compilation of file /home/tozkoparan/retdec/share/retdec/support/generic/yara_patterns/static-code/pe/64/le/x86/x64-debug-vs-2015.yara
Error: yarac failed during compilation of file /home/tozkoparan/retdec/share/retdec/support/generic/yara_patterns/static-code/pe/64/le/x86/x64-vs-2012.yara
```

**Comment by s3rvac** [comment] 2020-03-23 07:05
Hi. I have just tried a clean build on a fully upgraded Arch Linux machine and the installation finished without any issues. Could you please try running the following command and copy its output here?
```
/home/tozkoparan/retdec/bin/retdec-yarac -w /home/tozkoparan/retdec/share/retdec/support/generic/yara_patterns/static-code/pe/64/le/x86/x64-debug-vs-2015.yara /home/tozkoparan/retdec/share/retdec/support/generic/yara_patterns/static-code/pe/64/le/x86/x64-debug-vs-2015.yarac
```

**Comment by ahmedselim2017** [comment] 2020-03-23 11:34
Hi, the output of that command is:
```
/home/tozkoparan/retdec/share/retdec/support/generic/yara_patterns/static-code/pe/64/le/x86/x64-debug-vs-2015.yara(1): error: syntax error, unexpected identifier
/home/tozkoparan/retdec/share/retdec/support/generic/yara_patterns/static-code/pe/64/le/x86/x64-debug-vs-2015.yara(1): error: non-ascii character
```

**Comment by s3rvac** [comment] 2020-03-23 12:17
Could you please attach the following file to this issue? It seems that there is something wrong with it. (ZIP it if GitHub does not let you upload it.)
```
/home/tozkoparan/retdec/share/retdec/support/generic/yara_patterns/static-code/pe/64/le/x86/x64-debug-vs-2015.yara
```

**Comment by ahmedselim2017** [comment] 2020-03-23 13:51
[x64-debug-vs-2015.yara.zip](https://github.com/avast/retdec/files/4369707/x64-debug-vs-2015.yara.zip)

**Comment by s3rvac** [comment] 2020-03-23 13:58
Thank you. The attached file has already been compiled. This is strange as compiled files should end with `.yarac` (see [this function](https://github.com/avast/retdec/blob/020d242c619ca7a192560ed5d47770142bdec916/support/install-yara.py#L64)).

@ahmedselim2017 What commit (or source) are you trying to build? Is it the current `master` or some earlier release?

@metthal or @PeterMatula, do you have an idea what might have caused `.yara` files to be overwritten by their compiled versions?

**Comment by ahmedselim2017** [comment] 2020-03-23 14:03
I tried to build from master branch and also I have tried to install it from AUR packages (aur/retdec and aur/retdec-git) and get the same error.

**Comment by s3rvac** [comment] 2020-04-14 08:29
Hi. We were unable to determine the cause as we are unable to reproduce the issue. Could I please ask you to run the following commands and attach here the output here (files `cmake-output.txt`, `make-output.txt`, `make-install-output.txt`)?
```
$ git clone https://github.com/avast/retdec
$ mkdir build
$ cd build
$ cmake .. -DCMAKE_INSTALL_PREFIX=install |& tee cmake-output.txt
$ make -j$(nproc) |& tee make-output.txt
$ make install -j$(nproc) |& tee make-install-output.txt
```

**Comment by ahmedselim2017** [comment] 2020-04-15 20:57
Hİ, I ran that commands and interestingly, there was no issue. It installed Retdec successfully.
[make-install-output.txt](https://github.com/avast/retdec/files/4483703/make-install-output.txt)
[cmake-output.txt](https://github.com/avast/retdec/files/4483705/cmake-output.txt)
[make-output.txt](https://github.com/avast/retdec/files/4483706/make-output.txt)

**Comment by s3rvac** [comment] 2020-04-16 04:54
OK, great, thank you for the response! I am closing the issue as _cannot reproduce_. If you manage to reproduce it, you can re-open the issue, but we will need outputs from the three commands (`cmake`, `make`, `make install`).

**Closed by s3rvac** 2020-04-16 04:54 UTC
Labels: C-yara, P-install
