### ISSUE TITLE
`Compiler does not have C++17 filesystem feature`

### ISSUE THREAD

**Issue by catap** [avast/retdec#1002] opened 2021-08-15 18:07 UTC
Hey,

`cmake` durting configure decided that, let me quote:
```
2021-08-15T17:02:44.0016370Z -- -- Library stdc++fs NOT found -> linking utils without stdc++fs library
```

Anyway, build crashes with error:
```
2021-08-15T17:39:31.2269850Z cd /opt/local/var/macports/build/_Users_runner_work_1_s_ports_devel_retdec/retdec-devel/work/build/src/utils && /usr/bin/clang++ -DRETDEC_BUILD_DATE=\"2021-08-15T17:02:42Z\" -DRETDEC_GIT_COMMIT_HASH=\"GITDIR-NOTFOUND\" -DRETDEC_GIT_VERSION_TAG=\"HEAD-HASH-NOTFOUND\" -I/opt/local/var/macports/build/_Users_runner_work_1_s_ports_devel_retdec/retdec-devel/work/retdec-18b434f02b64bfb85232525ca10a6026b5d1f54f/include -I/opt/local/var/macports/build/_Users_runner_work_1_s_ports_devel_retdec/retdec-devel/work/retdec-18b434f02b64bfb85232525ca10a6026b5d1f54f/deps/whereami -pipe -Os -DNDEBUG -I/opt/local/include -stdlib=libc++ -isysroot/Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -fvisibility-inlines-hidden -Wall -Wextra -Wcast-align -Wcast-qual -Wswitch-default -Wuninitialized -Wold-style-cast -Wno-unused-parameter -arch x86_64 -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.14 -fPIC -std=c++17 -MD -MT src/utils/CMakeFiles/utils.dir/binary_path.cpp.o -MF CMakeFiles/utils.dir/binary_path.cpp.o.d -o CMakeFiles/utils.dir/binary_path.cpp.o -c /opt/local/var/macports/build/_Users_runner_work_1_s_ports_devel_retdec/retdec-devel/work/retdec-18b434f02b64bfb85232525ca10a6026b5d1f54f/src/utils/binary_path.cpp
2021-08-15T17:39:31.2542160Z In file included from /opt/local/var/macports/build/_Users_runner_work_1_s_ports_devel_retdec/retdec-devel/work/retdec-18b434f02b64bfb85232525ca10a6026b5d1f54f/src/utils/binary_path.cpp:9:
2021-08-15T17:39:31.2544360Z In file included from /opt/local/var/macports/build/_Users_runner_work_1_s_ports_devel_retdec/retdec-devel/work/retdec-18b434f02b64bfb85232525ca10a6026b5d1f54f/include/retdec/utils/binary_path.h:10:
2021-08-15T17:39:31.2547370Z /opt/local/var/macports/build/_Users_runner_work_1_s_ports_devel_retdec/retdec-devel/work/retdec-18b434f02b64bfb85232525ca10a6026b5d1f54f/include/retdec/utils/filesystem.h:19:3: error: "Compiler does not have C++17 filesystem feature."
2021-08-15T17:39:31.2548520Z         #error "Compiler does not have C++17 filesystem feature."
2021-08-15T17:39:31.2549080Z          ^
2021-08-15T17:39:31.2550300Z In file included from /opt/local/var/macports/build/_Users_runner_work_1_s_ports_devel_retdec/retdec-devel/work/retdec-18b434f02b64bfb85232525ca10a6026b5d1f54f/src/utils/binary_path.cpp:9:
2021-08-15T17:39:31.2551970Z /opt/local/var/macports/build/_Users_runner_work_1_s_ports_devel_retdec/retdec-devel/work/retdec-18b434f02b64bfb85232525ca10a6026b5d1f54f/include/retdec/utils/binary_path.h:15:1: error: use of undeclared identifier 'fs'
2021-08-15T17:39:31.2552850Z fs::path getThisBinaryPath();
2021-08-15T17:39:31.2553260Z ^
2021-08-15T17:39:31.2554510Z /opt/local/var/macports/build/_Users_runner_work_1_s_ports_devel_retdec/retdec-devel/work/retdec-18b434f02b64bfb85232525ca10a6026b5d1f54f/include/retdec/utils/binary_path.h:16:1: error: use of undeclared identifier 'fs'
2021-08-15T17:39:31.2555400Z fs::path getThisBinaryDirectoryPath();
2021-08-15T17:39:31.2555830Z ^
2021-08-15T17:39:31.2557330Z /opt/local/var/macports/build/_Users_runner_work_1_s_ports_devel_retdec/retdec-devel/work/retdec-18b434f02b64bfb85232525ca10a6026b5d1f54f/src/utils/binary_path.cpp:13:1: error: use of undeclared identifier 'std'
2021-08-15T17:39:31.2558220Z std::string getStringThisBinaryPath(
2021-08-15T17:39:31.2558600Z ^
2021-08-15T17:39:31.2559770Z /opt/local/var/macports/build/_Users_runner_work_1_s_ports_devel_retdec/retdec-devel/work/retdec-18b434f02b64bfb85232525ca10a6026b5d1f54f/src/utils/binary_path.cpp:14:3: error: use of undeclared identifier 'std'
2021-08-15T17:39:31.2560600Z                 std::size_t &directorySize)
2021-08-15T17:39:31.2561040Z                 ^
2021-08-15T17:39:31.2562250Z /opt/local/var/macports/build/_Users_runner_work_1_s_ports_devel_retdec/retdec-devel/work/retdec-18b434f02b64bfb85232525ca10a6026b5d1f54f/src/utils/binary_path.cpp:18:2: error: use of undeclared identifier 'std'
2021-08-15T17:39:31.2563060Z         std::string result;
2021-08-15T17:39:31.2563440Z         ^
2021-08-15T17:39:31.2565990Z /opt/local/var/macports/build/_Users_runner_work_1_s_ports_devel_retdec/retdec-devel/work/retdec-18b434f02b64bfb85232525ca10a6026b5d1f54f/src/utils/binary_path.cpp:21:35: error: use of undeclared identifier 'NULL'
2021-08-15T17:39:31.2566970Z         pathSize = wai_getExecutablePath(NULL, 0, &dirPathSize);
2021-08-15T17:39:31.2567490Z                                          ^
2021-08-15T17:39:31.2568830Z /opt/local/var/macports/build/_Users_runner_work_1_s_ports_devel_retdec/retdec-devel/work/retdec-18b434f02b64bfb85232525ca10a6026b5d1f54f/src/utils/binary_path.cpp:50:1: error: use of undeclared identifier 'fs'
2021-08-15T17:39:31.2569730Z fs::path getThisBinaryPath()
2021-08-15T17:39:31.2570140Z ^
2021-08-15T17:39:31.2571370Z /opt/local/var/macports/build/_Users_runner_work_1_s_ports_devel_retdec/retdec-devel/work/retdec-18b434f02b64bfb85232525ca10a6026b5d1f54f/src/utils/binary_path.cpp:52:2: error: use of undeclared identifier 'std'
2021-08-15T17:39:31.2572250Z         std::size_t dirPathSize = 0;
2021-08-15T17:39:31.2572690Z         ^
2021-08-15T17:39:31.2573880Z /opt/local/var/macports/build/_Users_runner_work_1_s_ports_devel_retdec/retdec-devel/work/retdec-18b434f02b64bfb85232525ca10a6026b5d1f54f/src/utils/binary_path.cpp:53:2: error: use of undeclared identifier 'std'
2021-08-15T17:39:31.2575040Z         std::string path = getStringThisBinaryPath(dirPathSize);
2021-08-15T17:39:31.2575530Z         ^
2021-08-15T17:39:31.2576770Z /opt/local/var/macports/build/_Users_runner_work_1_s_ports_devel_retdec/retdec-devel/work/retdec-18b434f02b64bfb85232525ca10a6026b5d1f54f/src/utils/binary_path.cpp:63:1: error: use of undeclared identifier 'fs'
2021-08-15T17:39:31.2577640Z fs::path getThisBinaryDirectoryPath()
2021-08-15T17:39:31.2578060Z ^
2021-08-15T17:39:31.2579360Z /opt/local/var/macports/build/_Users_runner_work_1_s_ports_devel_retdec/retdec-devel/work/retdec-18b434f02b64bfb85232525ca10a6026b5d1f54f/src/utils/binary_path.cpp:65:2: error: use of undeclared identifier 'std'
2021-08-15T17:39:31.2580220Z         std::size_t dirPathSize = 0;
2021-08-15T17:39:31.2580730Z         ^
2021-08-15T17:39:31.2582010Z /opt/local/var/macports/build/_Users_runner_work_1_s_ports_devel_retdec/retdec-devel/work/retdec-18b434f02b64bfb85232525ca10a6026b5d1f54f/src/utils/binary_path.cpp:66:2: error: use of undeclared identifier 'std'
2021-08-15T17:39:31.2582970Z         std::string path = getStringThisBinaryPath(dirPathSize);
2021-08-15T17:39:31.2583520Z         ^
2021-08-15T17:39:31.2584000Z 13 errors generated.
2021-08-15T17:39:31.2592190Z make[2]: *** [src/utils/CMakeFiles/utils.dir/binary_path.cpp.o] Error 1
2021-08-15T17:39:31.2593630Z make[2]: Leaving directory `/opt/local/var/macports/build/_Users_runner_work_1_s_ports_devel_retdec/retdec-devel/work/build'
2021-08-15T17:39:31.2594870Z make[1]: *** [src/utils/CMakeFiles/utils.dir/all] Error 2
2021-08-15T17:39:31.2596210Z make[1]: Leaving directory `/opt/local/var/macports/build/_Users_runner_work_1_s_ports_devel_retdec/retdec-devel/work/build'
2021-08-15T17:39:31.2598080Z make: *** [all] Error 2
2021-08-15T17:39:31.2599810Z make: Leaving directory `/opt/local/var/macports/build/_Users_runner_work_1_s_ports_devel_retdec/retdec-devel/work/build'
2021-08-15T17:39:31.2604350Z Command failed:  cd "/opt/local/var/macports/build/_Users_runner_work_1_s_ports_devel_retdec/retdec-devel/work/build" && /usr/bin/make -w all VERBOSE=ON 
2021-08-15T17:39:31.2605200Z Exit code: 2
2021-08-15T17:39:31.2610310Z Error: Failed to build retdec-devel: command execution failed
```

I'm using 18b434f02b64bfb85232525ca10a6026b5d1f54f as local root.

Thus, `v4.0` builds well on this machine.

To make it easy, I've attached the full log of building for both `v4.0` and `master`.

[12.txt](https://github.com/avast/retdec/files/6988617/12.txt)

**Comment by xkubov** [comment] 2021-08-16 07:10
Hi, the CMake message is not related to the error. It is useful only for `gcc`.

The problem is with `<filesystem>` include and its implementation in clang. The c++17 filesystem implementation in clang was included in macOS 10.15 ([Xcode release notes]) and from the logs, I see that you are using 10.14. I thought, however, that 10.14 does have experimental support. Can you check if you can compile a simple c++ program with the `<experimental/filesystem>` header?  There is a conditional include `<experimental/filesystem>` for this purpose in [`retdec/utils/filesystem.h`](https://github.com/avast/retdec/blob/master/include/retdec/utils/filesystem.h#L14).

**Comment by catap** [comment] 2021-08-16 08:19
@xkubov the hardest part: I haven't got access to this machine. I can reproduce it via macport's CI :)

Anyway, for me this issues related to unclear wording, nothing more.

**Comment by PeterMatula** [comment] 2021-08-23 07:45
> Anyway, for me this issues related to unclear wording, nothing more.

@xkubov can you please address this (e.g. better message) and close this?

**Comment by xkubov** [comment] 2021-08-25 15:16
I removed the cmake log message on macOS as it is misleading there. I left, however, the error message in the code as-is. The error message in `retdec/utils/filesystem.h` states that the compiler does not support c++17 features and RetDec now requires these features.

**Closed by xkubov** 2021-08-25 15:16 UTC
Labels: C-build-system
