### ISSUE TITLE
Update YARA to version 4.0.0

### ISSUE THREAD

**Issue by s3rvac** [avast/retdec#758] opened 2020-04-29 13:20 UTC
YARA 4.0.0 [was released](https://github.com/VirusTotal/yara/releases/tag/v4.0.0) on 2020-04-29. At the time of writing, RetDec uses YARA 3.11.0:

https://github.com/avast/retdec/blob/a728ec2d33643758301e5201f5b4319057d22eba/cmake/deps.cmake#L48

We should consider updating to 4.0.0. It will probably require some changes in RetDec as there were [API changes](https://github.com/VirusTotal/yara/wiki/Backward-incompatible-changes-in-YARA-4.0-API).

**Comment by PeterMatula** [comment] 2020-05-18 22:04
Because of #283, I would like to update to a specific (latest) commit in `master`, not the version tag. This would make adoption of improvements faster and more flexible. I hope YARA `master` is stable enough and if not, we would detect problems in our regression tests.
What do you think about this @metthal and @s3rvac?

**Comment by s3rvac** [comment] 2020-05-19 05:35
Will we want to update the used YARA version in RetDec more often than new releases of YARA are published? Wouldn't it be safer to just wait for official releases? They are quite frequent.

**Comment by PeterMatula** [comment] 2020-05-19 08:24
Not regularly, but in case of some bug fixes or added functionality we might. If we push for a fix or feature because we need it in RetDec, and it gets to YARA, it is more convenient to start using it right away and close the issue in question - as opposed to forget about it until the YARA release is out we need to come back to it.

**Comment by metthal** [comment] 2020-05-19 11:14
VirusTotal often uses non-released master branch in production so I would consider `master` to be stableish. There was some bugfixes since 4.0.0 and there's already 4.0.1. I usually wait a little bit until the changes settle in and serious bugs are resolved and then update to newer version.

**Closed** 2020-05-21 12:30 UTC
Labels: C-yara, enhancement
