### ISSUE TITLE
Add appveyor artifacts

### ISSUE THREAD

**Issue by Karaulov** [avast/retdec#551] opened 2019-04-18 04:16 UTC
Please add builded .zip to appveyor artifacts!

![AQxYfVs 1](https://user-images.githubusercontent.com/6445336/56336641-cf7db480-61a9-11e9-9f38-17cd2405f0f9.png)

is empty!

**Comment by s3rvac** [comment] 2019-04-18 07:54
Closing as a duplicate of #234 and #446, both of which you have submitted.

**Closed by s3rvac** 2019-04-18 07:54 UTC
